### ISSUE TITLE
[Question] 编辑配置文件并重新启动 mirai console 后配置文件被覆盖

### ISSUE THREAD

**Issue by weearc** [yyuueexxiinngg/onebot-kotlin#129]
关闭 mirai console 后尝试编辑了生成的配置文件，但编辑后重新启动 mirai console 配置文件被覆盖掉。使用的是Onebot 0.3.4 版本

**Comment by weearc** [comment]
由于前台调试bot时杀掉bot的进程或者重启进程时会提示找不到websocket监听的端口。因此onebot看起来会尝试覆写掉配置文件。但是这并不是我希望看到的。目前解决方案是用非root用户运行mirai console（因为出现过root身份执行后Java binary被覆盖并被加锁的情况）修改配置文件，修改attr权限，使之无法被删除或覆盖。
```bash
sudo chattr +i settings.yml
```

**Comment by yyuueexxiinngg** [comment]
配置文件的生成和读取都调用的console的api, 交由console进行管理, 当配置中存在`bots`项后应该是不会覆盖配置文件的, 请问修改的配置文件是怎样的?

**Comment by weearc** [comment]
> 配置文件的生成和读取都调用的console的api, 交由console进行管理, 当配置中存在`bots`项后应该是不会覆盖配置文件的, 请问修改的配置文件是怎样的?

对比 Readme 中的示例配置文件仅仅修改了 heartbeat enable 为true ，并开启了 ws 和 ws reverse 。在调试bot代码过程中由于 websocket 中断，mirai console 回报无法找到相应 websocket 监听的端口。未对配置文件加锁前会被尝试覆盖。加锁后 mirai console 报错无法对onebot的配置文件进行写入（以非root运行的mirai console）

**Comment by yyuueexxiinngg** [comment]
配置是复制README示例中的内容吗, 如果是, 则确实会被覆盖, 因为示例中并未将配置项写全, 请修改被覆盖后的配置文件试试

而且理论上覆盖不会丢失修改的内容

**Comment by a08381** [comment]
> 配置是复制README示例中的内容吗, 如果是, 则确实会被覆盖, 因为示例中并未将配置项写全, 请修改被覆盖后的配置文件试试
> 
> 而且理论上覆盖不会丢失修改的内容

我这边也遇到了，复现方法：
正常使用中的配置
修改http.enable为false
supervisor重启mirai
重启后http.enable恢复为true

**Comment by a08381** [comment]
配置文件样式：

```yaml
proxy: ''
db: 
  enable: true
  # 生存时间/小时，存储的消息会在超过此时间后过期删除，设置为非正数视为无限
  ttl: 72
bots: 
  314****867: 
    cacheImage: true
    cacheRecord: true
    heartbeat: 
      enable: true
      interval: 1500
    http: 
      enable: true
      host: 0.0.0.0
      port: 5700
      accessToken: ''
      postUrl: ''
      postMessageFormat: string
      secret: ''
      # 上报超时时间, 单位毫秒, 须大于0才会生效
      timeout: 0
    ws_reverse: 
      - enable: true
        postMessageFormat: string
        reverseHost: 127.0.0.1
        reversePort: 8002
        accessToken: qwerty*******
        reversePath: '/ws'
        reverseApiPath: '/api'
        reverseEventPath: '/event'
        useUniversal: true
        useTLS: false
        reconnectInterval: 3000
    ws: 
      enable: false
      postMessageFormat: string
      wsHost: 0.0.0.0
      wsPort: 6700
      accessToken: ''
```
